### ISSUE TITLE
Link Resources in NC-Appstore to github

### ISSUE THREAD

**Issue by JSoko** [juliushaertl/issuetemplate#12]
In the nc-Appstore https://apps.nextcloud.com/apps/issuetemplate
under **Resources** there should be at least a link to github
https://github.com/juliushaertl/issuetemplate

Ps.: Thanks for Your work and for 0.2 :-))

**Comment by juliushaertl** [comment]
Ah thanks, we need to add the repo and issue tracking links to the appinfo.xml file, as described here:
https://nextcloudappstore.readthedocs.io/en/latest/developer.html#info-xml
