### ISSUE TITLE
errors in Nextcloud log

### ISSUE THREAD

**Issue by stanelie** [juliushaertl/issuetemplate#13]
Hello.

The Issue Template app generates some errors in my Nextcloud log. I am running Nextcloud 11.0.1.

 The first error line is
> get_browser(): browscap ini directive not set at /var/www/nextcloud/apps/issuetemplate/lib/Settings/Admin.php#262

and then, I get 

> Undefined index: bugs at /var/www/nextcloud/apps/issuetemplate/lib/Settings/Admin.php#215

about 20 times.

**Comment by juliushaertl** [comment]
@stanelie Thanks for the report. I'll have a look at it. 

> get_browser(): browscap ini directive not set at /var/www/nextcloud/apps/issuetemplate/lib/Settings/Admin.php#262

This can be fixed by adding a browercap file to your server config http://stackoverflow.com/questions/2036956/browscap-ini-directive-not-set#2036968 But at least the error should not mess up the server logs.

**Comment by stanelie** [comment]
I've adjusted the browscap setting in php.ini and that error is gone.

Noe, the first error message in the log is

`Undefined index: plattform at /var/www/nextcloud/apps/issuetemplate/lib/Settings/Admin.php#266`

before the multiple `Undefined index: bugs at /var/www/nextcloud/apps/issuetemplate/lib/Settings/Admin.php#215`

**Comment by juliushaertl** [comment]
@stanelie Those should be fixed now on master. Thanks again for reporting.
