### ISSUE TITLE
error in nextcloud log

### ISSUE THREAD

**Issue by stanelie** [juliushaertl/issuetemplate#14]
Hello again.

The new build gives out another error in the log : 
`Undefined index: plattform at /var/www/nextcloud/apps/issuetemplate/lib/Settings/Admin.php#266`

**Comment by juliushaertl** [comment]
@stanelie Thanks for reporting. I've added another check for those in f9ef0ef.

**Comment by stanelie** [comment]
Works.
Thanks!
