### ISSUE TITLE
Missing Gallery entry

### ISSUE THREAD

**Issue by oparoz** [juliushaertl/issuetemplate#15]
Gallery is shipped with the server, but is a separate app, so it needs to be added as an additional entry (for now)

**Comment by oparoz** [comment]
Should I just add it here?:
https://github.com/juliushaertl/issuetemplate/blob/51fa558553f5d8e937962b41c57bf537c2befc5c/lib/Settings/Admin.php#L212

**Comment by juliushaertl** [comment]
It would make more sense to me to just add <bugs> tag to the gallery appinfo.xml so we don't have to much hard coded stuff in here. Or am I missing some reason why it shouldn't be in there?

**Comment by oparoz** [comment]
If that's all it takes, then yes, it's easier. I wasn't sure what you were using :)

**Comment by juliushaertl** [comment]
Sure, that should be documented somewhere. :see_no_evil:
